name: Tag with Memcached versions
on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron: '0 0 * * 1'
jobs:
  tag:
    runs-on: ubuntu-latest
    environment: pull-tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Get AWS Elasticache versions
        run: |
          aws elasticache describe-cache-engine-versions --engine memcached --query "CacheEngineVersions[*].{version:EngineVersion}" --output json > versions.json
      - name: Read versions from JSON file
        id: versions
        run: |
          VERSIONS=$(jq -r '.[].version' versions.json | paste -sd " " -)
          echo "::set-output name=versions::$VERSIONS"
      - name: Create tags for each version
        run: |
          chmod +x ./create-tags.sh
          read -a VERSIONS <<< "${{ steps.versions.outputs.versions }}"
          ./create-tags.sh "${VERSIONS[@]}"
